branches:
  only:
  - tmn505

arch:
  - amd64

os: linux

dist: bionic

env:
  - REPONAME=$(basename $TRAVIS_REPO_SLUG) ALARCH=x86_64

language: generic

addons:
  apt:
    packages:
      - asciidoc
      - libarchive-tools
      - xsltproc
      - zstd

git:
  quiet: true

cache:
  directories:
    - $HOME/src

before_script:
  - sudo mkdir -p /run/shm/
  - git clone https://git.archlinux.org/arch-install-scripts.git $HOME/arch-install-scripts
  - make -j2 -C $HOME/arch-install-scripts
  - sudo make -C $HOME/arch-install-scripts install
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git --branch gh-pages --single-branch $HOME/repo || true
  - rm -fR $HOME/repo/.git

script:
  - sudo ./.ci/mkrepo.sh $USER $TRAVIS_BUILD_DIR $ALARCH

before_deploy:
  - sudo chown -R $USER:$USER $HOME/repo
  - ./.ci/createlinks.sh $HOME/repo $REPONAME
  - ./.ci/genindex.sh $HOME/repo $REPONAME

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  skip_cleanup: true
  local_dir: $HOME/repo/
  on:
    repo: $TRAVIS_REPO_SLUG
    branch: tmn505
